---
title: "ANGSD HW1"
author: "Caden McQuillen"
date: '2023-01-12'
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Question 1
```{bash Question 1, eval = FALSE}
cd /home/cnm4001
mkdir angsd_hw
cd angsd_hw
mkdir hw1
cd hw1
```
## Question 2
```{bash Question 2, eval = FALSE}
cp /home/luce/angsd/demo-data/demo.fastq .
ls
demo.fastq
```
## Question 3
```{bash Question 3, eval = FALSE}
wc -l demo.fastq
100000 demo.fastq

```
## Question 4
```{bash Question 4, eval = FALSE}
wget https://hgdownload.soe.ucsc.edu/goldenPath/sacCer3/bigZips/sacCer3.chrom.sizes
wget https://hgdownload.soe.ucsc.edu/goldenPath/sacCer2/bigZips/sacCer2.chrom.sizes
wget https://hgdownload.soe.ucsc.edu/goldenPath/sacCer1/bigZips/sacCer1.chrom.sizes
ls
demo.fastq  sacCer1.chrom.sizes  sacCer2.chrom.sizes  sacCer3.chrom.sizes

```
## Question 5
```{bash Question 5, eval = FALSE}
file * | less
demo.fastq:          ASCII text
sacCer1.chrom.sizes: ASCII text
sacCer2.chrom.sizes: ASCII text
sacCer3.chrom.sizes: ASCII text

cat sacCer1.chrom.sizes 
chr1	230208
chr10	745446
chr11	666445
chr12	1078173
chr13	924430
chr14	784328
chr15	1091285
chr16	948060
chr2	813136
chr3	316613
chr4	1531914
chr5	576869
chr6	270148
chr7	1090944
chr8	562639
chr9	439885
chrM	85779

cat sacCer2.chrom.sizes 
chrIV	1531919
chrXV	1091289
chrVII	1090947
chrXII	1078175
chrXVI	948062
chrXIII	924429
chrII	813178
chrXIV	784333
chrX	745742
chrXI	666454
chrV	576869
chrVIII	562643
chrIX	439885
chrIII	316617
chrVI	270148
chrI	230208
chrM	85779
2micron	6318

cat sacCer3.chrom.sizes 
chrIV	1531933
chrXV	1091291
chrVII	1090940
chrXII	1078177
chrXVI	948066
chrXIII	924431
chrII	813184
chrXIV	784333
chrX	745751
chrXI	666816
chrV	576874
chrVIII	562643
chrIX	439888
chrIII	316620
chrVI	270161
chrI	230218
chrM	85779

```
## Question 6

| File                | Chr     | Size    |
|---------------------|---------|---------|
| sacCer1.chrom.sizes | chr1    | 230208  |
| sacCer1.chrom.sizes | chr10   | 745446  |
| sacCer1.chrom.sizes | chr11   | 666445  |
| sacCer1.chrom.sizes | chr12   | 1078173 |
| sacCer1.chrom.sizes | chr13   | 924430  |
| sacCer1.chrom.sizes | chr14   | 784328  |
| sacCer1.chrom.sizes | chr15   | 1091285 |
| sacCer1.chrom.sizes | chr16   | 948060  |
| sacCer1.chrom.sizes | chr2    | 813136  |
| sacCer1.chrom.sizes | chr3    | 316613  |
| sacCer1.chrom.sizes | chr4    | 1531914 |
| sacCer1.chrom.sizes | chr5    | 576869  |
| sacCer1.chrom.sizes | chr6    | 270148  |
| sacCer1.chrom.sizes | chr7    | 1090944 |
| sacCer1.chrom.sizes | chr8    | 562639  |
| sacCer1.chrom.sizes | chr9    | 439885  |
| sacCer1.chrom.sizes | chrM    | 85779   |
| sacCer2.chrom.sizes | chrIV   | 1531919 |
| sacCer2.chrom.sizes | chrXV   | 1091289 |
| sacCer2.chrom.sizes | chrVII  | 1090947 |
| sacCer2.chrom.sizes | chrXII  | 1078175 |
| sacCer2.chrom.sizes | chrXVI  | 948062  |
| sacCer2.chrom.sizes | chrXIII | 924429  |
| sacCer2.chrom.sizes | chrII   | 813178  |
| sacCer2.chrom.sizes | chrXIV  | 784333  |
| sacCer2.chrom.sizes | chrX    | 745742  |
| sacCer2.chrom.sizes | chrXI   | 666454  |
| sacCer2.chrom.sizes | chrV    | 576869  |
| sacCer2.chrom.sizes | chrVIII | 562643  |
| sacCer2.chrom.sizes | chrIX   | 439885  |
| sacCer2.chrom.sizes | chrIII  | 316617  |
| sacCer2.chrom.sizes | chrVI   | 270148  |
| sacCer2.chrom.sizes | chrI    | 230208  |
| sacCer2.chrom.sizes | chrM    | 85779   |
| sacCer2.chrom.sizes | 2micron | 6318    |
| sacCer3.chrom.sizes | chrIV   | 1531933 |
| sacCer3.chrom.sizes | chrXV   | 1091291 |
| sacCer3.chrom.sizes | chrVII  | 1090940 |
| sacCer3.chrom.sizes | chrXII  | 1078177 |
| sacCer3.chrom.sizes | chrXVI  | 948066  |
| sacCer3.chrom.sizes | chrXIII | 924431  |
| sacCer3.chrom.sizes | chrII   | 813184  |
| sacCer3.chrom.sizes | chrXIV  | 784333  |
| sacCer3.chrom.sizes | chrX    | 745751  |
| sacCer3.chrom.sizes | chrXI   | 666816  |
| sacCer3.chrom.sizes | chrV    | 576874  |
| sacCer3.chrom.sizes | chrVIII | 562643  |
| sacCer3.chrom.sizes | chrIX   | 439888  |
| sacCer3.chrom.sizes | chrIII  | 316620  |
| sacCer3.chrom.sizes | chrVI   | 270161  |
| sacCer3.chrom.sizes | chrI    | 230218  |
| sacCer3.chrom.sizes | chrM    | 85779   |

